export enum employeeActionTypes {
  FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST',
  FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS',
  FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE'
}
