export enum employeeActionTypes {
  FETCH_EMPLOYEES_REQUEST = 'FETCH_EMPLOYEES_REQUEST',
  FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS',
  FETCH_EMPLOYEES_FAILURE = 'FETCH_EMPLOYEES_FAILURE',

  UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST',
  UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS',
  UPDATE_EMPLOYEE_FAILURE = 'UPDATE_EMPLOYEE_FAILURE'
}
